name: Deploy React App

on:
  push:
    branches:
      - main  # Or your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build
      env:
        REACT_APP_API_KEY_EXT: ${{ secrets.REACT_APP_API_KEY }}
        REACT_APP_AUTH_DOMAIN_EXT: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
        REACT_APP_PROJECT_ID_EXT: ${{ secrets.REACT_APP_PROJECT_ID }}
        REACT_APP_STORAGE_BUCKET_EXT: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
        REACT_APP_MESSAGING_SENDER_ID_EXT: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
        REACT_APP_APP_ID_EXT: ${{ secrets.REACT_APP_APP_ID }}
        REACT_APP_CAPTCHA_API_KEY_EXT:  ${{ secrets.REACT_APP_CAPTCHA_API_KEY }}

    - name: List output files
      run: find build/ -print
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
          server: ${{ secrets.FTP_HOST }} 
          username: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./
          local-dir: build/


